# Generated by Django 5.2.17 on 2026-09-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.PositiveIntegerField(db_index=True)),
                ('iniciada_em', models.DateTimeField()),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('linhas', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('sucesso', 'Sucesso'), ('inalterada', 'Inalterada'), ('falha', 'Falha')], default='em_andamento', max_length=20)),
                ('erro', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'carga',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='StagingMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.PositiveIntegerField()),
                ('produto_codigo', models.CharField(max_length=20)),
                ('produto_nome', models.CharField(max_length=200)),
                ('indicador_codigo', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=100)),
                ('municipio_codigo', models.CharField(max_length=7)),
                ('municipio_nome', models.CharField(max_length=100)),
                ('ano', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=22, null=True)),
                ('status_valor', models.CharField(max_length=12)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging', to='ingestao.carga')),
            ],
            options={
                'db_table': 'staging_medicao',
            },
        ),
    ]
