# Generated by Django 5.2.17 on 2026-09-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('codigo_ibge', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('agregacao', models.CharField(choices=[('soma', 'Soma'), ('media_ponderada', 'Média ponderada'), ('nao_agregavel', 'Não agregável')], max_length=20)),
            ],
            options={
                'db_table': 'dim_indicador',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_ibge', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('microrregiao', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'dim_municipio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('codigo_ibge', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('segmento', models.CharField(choices=[('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária')], max_length=20)),
                ('tabela_origem', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'dim_produto',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('tabela_origem', 'codigo_ibge'), name='produto_unico_por_tabela')],
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=22, null=True)),
                ('status_valor', models.CharField(choices=[('ok', 'Ok'), ('sigiloso', 'Sigiloso'), ('inexistente', 'Inexistente')], max_length=12)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='ingestao.carga')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='indicadores.indicador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='indicadores.municipio')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='indicadores.produto')),
            ],
            options={
                'db_table': 'fato_medicao',
                'indexes': [models.Index(fields=['produto', 'indicador', 'ano'], name='medicao_recorte')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'indicador', 'municipio', 'ano'), name='medicao_unica'), models.CheckConstraint(condition=models.Q(models.Q(('status_valor', 'ok'), ('valor__isnull', False)), models.Q(models.Q(('status_valor', 'ok'), _negated=True), ('valor__isnull', True)), _connector='OR'), name='medicao_valor_coerente_com_status')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='indicadores.indicador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='indicadores.produto')),
            ],
            options={
                'db_table': 'dim_produto_indicador',
                'constraints': [models.UniqueConstraint(fields=('produto', 'indicador'), name='produto_indicador_unico')],
            },
        ),
    ]
