# Generated by Django 5.2.17 on 2026-10-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_mv_ranking'),
        ('ingestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicePreco',
            fields=[
                ('ano', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('indice_medio', models.DecimalField(decimal_places=6, max_digits=22)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indices', to='ingestao.carga')),
            ],
            options={
                'db_table': 'dim_indice_preco',
                'ordering': ['ano'],
            },
        ),
    ]
