# Generated by Django 5.2.17 on 2026-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, unique=True)),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('pdf', models.BinaryField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'relatorio',
            },
        ),
    ]
